platform :ios, '9.0'
use_frameworks!

target 'xpayr' do
  pod 'SwipeCellKit'
  pod 'IQKeyboardManager'
  pod 'Disk', '~> 0.3.1'
  pod 'lottie-ios'
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'Firebase/RemoteConfig'
end
